// Generated by gencpp from file state_estimator_msgs/actuatorForces.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_ACTUATORFORCES_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_ACTUATORFORCES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct actuatorForces_
{
  typedef actuatorForces_<ContainerAllocator> Type;

  actuatorForces_()
    : tau()  {
      tau.assign(0.0);
  }
  actuatorForces_(const ContainerAllocator& _alloc)
    : tau()  {
  (void)_alloc;
      tau.assign(0.0);
  }



   typedef boost::array<double, 12>  _tau_type;
  _tau_type tau;





  typedef boost::shared_ptr< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> const> ConstPtr;

}; // struct actuatorForces_

typedef ::state_estimator_msgs::actuatorForces_<std::allocator<void> > actuatorForces;

typedef boost::shared_ptr< ::state_estimator_msgs::actuatorForces > actuatorForcesPtr;
typedef boost::shared_ptr< ::state_estimator_msgs::actuatorForces const> actuatorForcesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::actuatorForces_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::actuatorForces_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::actuatorForces_<ContainerAllocator2> & rhs)
{
  return lhs.tau == rhs.tau;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::actuatorForces_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::actuatorForces_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba60240ffc5d00ebf671ed99a32a8ab5";
  }

  static const char* value(const ::state_estimator_msgs::actuatorForces_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba60240ffc5d00ebULL;
  static const uint64_t static_value2 = 0xf671ed99a32a8ab5ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/actuatorForces";
  }

  static const char* value(const ::state_estimator_msgs::actuatorForces_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[12] tau\n"
;
  }

  static const char* value(const ::state_estimator_msgs::actuatorForces_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tau);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct actuatorForces_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::actuatorForces_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::actuatorForces_<ContainerAllocator>& v)
  {
    s << indent << "tau[]" << std::endl;
    for (size_t i = 0; i < v.tau.size(); ++i)
    {
      s << indent << "  tau[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tau[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_ACTUATORFORCES_H
