// Generated by gencpp from file state_estimator_msgs/getActiveEstimators.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_GETACTIVEESTIMATORS_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_GETACTIVEESTIMATORS_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/getActiveEstimatorsRequest.h>
#include <state_estimator_msgs/getActiveEstimatorsResponse.h>


namespace state_estimator_msgs
{

struct getActiveEstimators
{

typedef getActiveEstimatorsRequest Request;
typedef getActiveEstimatorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getActiveEstimators
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::getActiveEstimators > {
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::state_estimator_msgs::getActiveEstimators&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::getActiveEstimators > {
  static const char* value()
  {
    return "state_estimator_msgs/getActiveEstimators";
  }

  static const char* value(const ::state_estimator_msgs::getActiveEstimators&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::getActiveEstimatorsRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::getActiveEstimators >
template<>
struct MD5Sum< ::state_estimator_msgs::getActiveEstimatorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::getActiveEstimators >::value();
  }
  static const char* value(const ::state_estimator_msgs::getActiveEstimatorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::getActiveEstimatorsRequest> should match
// service_traits::DataType< ::state_estimator_msgs::getActiveEstimators >
template<>
struct DataType< ::state_estimator_msgs::getActiveEstimatorsRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::getActiveEstimators >::value();
  }
  static const char* value(const ::state_estimator_msgs::getActiveEstimatorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::getActiveEstimatorsResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::getActiveEstimators >
template<>
struct MD5Sum< ::state_estimator_msgs::getActiveEstimatorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::getActiveEstimators >::value();
  }
  static const char* value(const ::state_estimator_msgs::getActiveEstimatorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::getActiveEstimatorsResponse> should match
// service_traits::DataType< ::state_estimator_msgs::getActiveEstimators >
template<>
struct DataType< ::state_estimator_msgs::getActiveEstimatorsResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::getActiveEstimators >::value();
  }
  static const char* value(const ::state_estimator_msgs::getActiveEstimatorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_GETACTIVEESTIMATORS_H
