// Generated by gencpp from file state_estimator_msgs/getActiveEstimatorsRequest.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_GETACTIVEESTIMATORSREQUEST_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_GETACTIVEESTIMATORSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct getActiveEstimatorsRequest_
{
  typedef getActiveEstimatorsRequest_<ContainerAllocator> Type;

  getActiveEstimatorsRequest_()
    {
    }
  getActiveEstimatorsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct getActiveEstimatorsRequest_

typedef ::state_estimator_msgs::getActiveEstimatorsRequest_<std::allocator<void> > getActiveEstimatorsRequest;

typedef boost::shared_ptr< ::state_estimator_msgs::getActiveEstimatorsRequest > getActiveEstimatorsRequestPtr;
typedef boost::shared_ptr< ::state_estimator_msgs::getActiveEstimatorsRequest const> getActiveEstimatorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/getActiveEstimatorsRequest";
  }

  static const char* value(const ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getActiveEstimatorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::state_estimator_msgs::getActiveEstimatorsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_GETACTIVEESTIMATORSREQUEST_H
