// Generated by gencpp from file state_estimator_msgs/getBlacklist.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_GETBLACKLIST_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_GETBLACKLIST_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/getBlacklistRequest.h>
#include <state_estimator_msgs/getBlacklistResponse.h>


namespace state_estimator_msgs
{

struct getBlacklist
{

typedef getBlacklistRequest Request;
typedef getBlacklistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getBlacklist
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::getBlacklist > {
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::state_estimator_msgs::getBlacklist&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::getBlacklist > {
  static const char* value()
  {
    return "state_estimator_msgs/getBlacklist";
  }

  static const char* value(const ::state_estimator_msgs::getBlacklist&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::getBlacklistRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::getBlacklist >
template<>
struct MD5Sum< ::state_estimator_msgs::getBlacklistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::getBlacklist >::value();
  }
  static const char* value(const ::state_estimator_msgs::getBlacklistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::getBlacklistRequest> should match
// service_traits::DataType< ::state_estimator_msgs::getBlacklist >
template<>
struct DataType< ::state_estimator_msgs::getBlacklistRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::getBlacklist >::value();
  }
  static const char* value(const ::state_estimator_msgs::getBlacklistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::getBlacklistResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::getBlacklist >
template<>
struct MD5Sum< ::state_estimator_msgs::getBlacklistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::getBlacklist >::value();
  }
  static const char* value(const ::state_estimator_msgs::getBlacklistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::getBlacklistResponse> should match
// service_traits::DataType< ::state_estimator_msgs::getBlacklist >
template<>
struct DataType< ::state_estimator_msgs::getBlacklistResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::getBlacklist >::value();
  }
  static const char* value(const ::state_estimator_msgs::getBlacklistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_GETBLACKLIST_H
