// Generated by gencpp from file state_estimator_msgs/getBlacklistResponse.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_GETBLACKLISTRESPONSE_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_GETBLACKLISTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct getBlacklistResponse_
{
  typedef getBlacklistResponse_<ContainerAllocator> Type;

  getBlacklistResponse_()
    : names()  {
    }
  getBlacklistResponse_(const ContainerAllocator& _alloc)
    : names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _names_type;
  _names_type names;





  typedef boost::shared_ptr< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getBlacklistResponse_

typedef ::state_estimator_msgs::getBlacklistResponse_<std::allocator<void> > getBlacklistResponse;

typedef boost::shared_ptr< ::state_estimator_msgs::getBlacklistResponse > getBlacklistResponsePtr;
typedef boost::shared_ptr< ::state_estimator_msgs::getBlacklistResponse const> getBlacklistResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator2> & rhs)
{
  return lhs.names == rhs.names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc7ae3609524b180ULL;
  static const uint64_t static_value2 = 0x34e49294a4ce670eULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/getBlacklistResponse";
  }

  static const char* value(const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] names\n"
"\n"
;
  }

  static const char* value(const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getBlacklistResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::getBlacklistResponse_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_GETBLACKLISTRESPONSE_H
