// Generated by gencpp from file state_estimator_msgs/getEstimatorDescription.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_GETESTIMATORDESCRIPTION_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_GETESTIMATORDESCRIPTION_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/getEstimatorDescriptionRequest.h>
#include <state_estimator_msgs/getEstimatorDescriptionResponse.h>


namespace state_estimator_msgs
{

struct getEstimatorDescription
{

typedef getEstimatorDescriptionRequest Request;
typedef getEstimatorDescriptionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getEstimatorDescription
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::getEstimatorDescription > {
  static const char* value()
  {
    return "12c3019909e7fa7b3482cdf9594556c2";
  }

  static const char* value(const ::state_estimator_msgs::getEstimatorDescription&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::getEstimatorDescription > {
  static const char* value()
  {
    return "state_estimator_msgs/getEstimatorDescription";
  }

  static const char* value(const ::state_estimator_msgs::getEstimatorDescription&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::getEstimatorDescriptionRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::getEstimatorDescription >
template<>
struct MD5Sum< ::state_estimator_msgs::getEstimatorDescriptionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::getEstimatorDescription >::value();
  }
  static const char* value(const ::state_estimator_msgs::getEstimatorDescriptionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::getEstimatorDescriptionRequest> should match
// service_traits::DataType< ::state_estimator_msgs::getEstimatorDescription >
template<>
struct DataType< ::state_estimator_msgs::getEstimatorDescriptionRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::getEstimatorDescription >::value();
  }
  static const char* value(const ::state_estimator_msgs::getEstimatorDescriptionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::getEstimatorDescriptionResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::getEstimatorDescription >
template<>
struct MD5Sum< ::state_estimator_msgs::getEstimatorDescriptionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::getEstimatorDescription >::value();
  }
  static const char* value(const ::state_estimator_msgs::getEstimatorDescriptionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::getEstimatorDescriptionResponse> should match
// service_traits::DataType< ::state_estimator_msgs::getEstimatorDescription >
template<>
struct DataType< ::state_estimator_msgs::getEstimatorDescriptionResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::getEstimatorDescription >::value();
  }
  static const char* value(const ::state_estimator_msgs::getEstimatorDescriptionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_GETESTIMATORDESCRIPTION_H
