// Generated by gencpp from file state_estimator_msgs/getWhitelist.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_GETWHITELIST_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_GETWHITELIST_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/getWhitelistRequest.h>
#include <state_estimator_msgs/getWhitelistResponse.h>


namespace state_estimator_msgs
{

struct getWhitelist
{

typedef getWhitelistRequest Request;
typedef getWhitelistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getWhitelist
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::getWhitelist > {
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::state_estimator_msgs::getWhitelist&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::getWhitelist > {
  static const char* value()
  {
    return "state_estimator_msgs/getWhitelist";
  }

  static const char* value(const ::state_estimator_msgs::getWhitelist&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::getWhitelistRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::getWhitelist >
template<>
struct MD5Sum< ::state_estimator_msgs::getWhitelistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::getWhitelist >::value();
  }
  static const char* value(const ::state_estimator_msgs::getWhitelistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::getWhitelistRequest> should match
// service_traits::DataType< ::state_estimator_msgs::getWhitelist >
template<>
struct DataType< ::state_estimator_msgs::getWhitelistRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::getWhitelist >::value();
  }
  static const char* value(const ::state_estimator_msgs::getWhitelistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::getWhitelistResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::getWhitelist >
template<>
struct MD5Sum< ::state_estimator_msgs::getWhitelistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::getWhitelist >::value();
  }
  static const char* value(const ::state_estimator_msgs::getWhitelistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::getWhitelistResponse> should match
// service_traits::DataType< ::state_estimator_msgs::getWhitelist >
template<>
struct DataType< ::state_estimator_msgs::getWhitelistResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::getWhitelist >::value();
  }
  static const char* value(const ::state_estimator_msgs::getWhitelistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_GETWHITELIST_H
