// Generated by gencpp from file state_estimator_msgs/imu.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_IMU_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct imu_
{
  typedef imu_<ContainerAllocator> Type;

  imu_()
    : w()
    , a()  {
      w.assign(0.0);

      a.assign(0.0);
  }
  imu_(const ContainerAllocator& _alloc)
    : w()
    , a()  {
  (void)_alloc;
      w.assign(0.0);

      a.assign(0.0);
  }



   typedef boost::array<double, 3>  _w_type;
  _w_type w;

   typedef boost::array<double, 3>  _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::state_estimator_msgs::imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::imu_<ContainerAllocator> const> ConstPtr;

}; // struct imu_

typedef ::state_estimator_msgs::imu_<std::allocator<void> > imu;

typedef boost::shared_ptr< ::state_estimator_msgs::imu > imuPtr;
typedef boost::shared_ptr< ::state_estimator_msgs::imu const> imuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::imu_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::imu_<ContainerAllocator2> & rhs)
{
  return lhs.w == rhs.w &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::imu_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::imu_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::imu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3eb7a1d5e42bc0c9297c14a9acbb436b";
  }

  static const char* value(const ::state_estimator_msgs::imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3eb7a1d5e42bc0c9ULL;
  static const uint64_t static_value2 = 0x297c14a9acbb436bULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/imu";
  }

  static const char* value(const ::state_estimator_msgs::imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] w\n"
"float64[3] a\n"
;
  }

  static const char* value(const ::state_estimator_msgs::imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::imu_<ContainerAllocator>& v)
  {
    s << indent << "w[]" << std::endl;
    for (size_t i = 0; i < v.w.size(); ++i)
    {
      s << indent << "  w[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.w[i]);
    }
    s << indent << "a[]" << std::endl;
    for (size_t i = 0; i < v.a.size(); ++i)
    {
      s << indent << "  a[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.a[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_IMU_H
