// Generated by gencpp from file state_estimator_msgs/jointState.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_JOINTSTATE_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_JOINTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct jointState_
{
  typedef jointState_<ContainerAllocator> Type;

  jointState_()
    : q()  {
      q.assign(0.0);
  }
  jointState_(const ContainerAllocator& _alloc)
    : q()  {
  (void)_alloc;
      q.assign(0.0);
  }



   typedef boost::array<double, 12>  _q_type;
  _q_type q;





  typedef boost::shared_ptr< ::state_estimator_msgs::jointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::jointState_<ContainerAllocator> const> ConstPtr;

}; // struct jointState_

typedef ::state_estimator_msgs::jointState_<std::allocator<void> > jointState;

typedef boost::shared_ptr< ::state_estimator_msgs::jointState > jointStatePtr;
typedef boost::shared_ptr< ::state_estimator_msgs::jointState const> jointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::jointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::jointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::jointState_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::jointState_<ContainerAllocator2> & rhs)
{
  return lhs.q == rhs.q;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::jointState_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::jointState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::jointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::jointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::jointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::jointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::jointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::jointState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::jointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0439c8b99a1acbdc6519301f07a67111";
  }

  static const char* value(const ::state_estimator_msgs::jointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0439c8b99a1acbdcULL;
  static const uint64_t static_value2 = 0x6519301f07a67111ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::jointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/jointState";
  }

  static const char* value(const ::state_estimator_msgs::jointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::jointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[12] q\n"
;
  }

  static const char* value(const ::state_estimator_msgs::jointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::jointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::jointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::jointState_<ContainerAllocator>& v)
  {
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_JOINTSTATE_H
