// Generated by gencpp from file state_estimator_msgs/listAllEstimators.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_LISTALLESTIMATORS_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_LISTALLESTIMATORS_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/listAllEstimatorsRequest.h>
#include <state_estimator_msgs/listAllEstimatorsResponse.h>


namespace state_estimator_msgs
{

struct listAllEstimators
{

typedef listAllEstimatorsRequest Request;
typedef listAllEstimatorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct listAllEstimators
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::listAllEstimators > {
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::state_estimator_msgs::listAllEstimators&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::listAllEstimators > {
  static const char* value()
  {
    return "state_estimator_msgs/listAllEstimators";
  }

  static const char* value(const ::state_estimator_msgs::listAllEstimators&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::listAllEstimatorsRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::listAllEstimators >
template<>
struct MD5Sum< ::state_estimator_msgs::listAllEstimatorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::listAllEstimators >::value();
  }
  static const char* value(const ::state_estimator_msgs::listAllEstimatorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::listAllEstimatorsRequest> should match
// service_traits::DataType< ::state_estimator_msgs::listAllEstimators >
template<>
struct DataType< ::state_estimator_msgs::listAllEstimatorsRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::listAllEstimators >::value();
  }
  static const char* value(const ::state_estimator_msgs::listAllEstimatorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::listAllEstimatorsResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::listAllEstimators >
template<>
struct MD5Sum< ::state_estimator_msgs::listAllEstimatorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::listAllEstimators >::value();
  }
  static const char* value(const ::state_estimator_msgs::listAllEstimatorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::listAllEstimatorsResponse> should match
// service_traits::DataType< ::state_estimator_msgs::listAllEstimators >
template<>
struct DataType< ::state_estimator_msgs::listAllEstimatorsResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::listAllEstimators >::value();
  }
  static const char* value(const ::state_estimator_msgs::listAllEstimatorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_LISTALLESTIMATORS_H
