// Generated by gencpp from file state_estimator_msgs/listAllEstimatorsRequest.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_LISTALLESTIMATORSREQUEST_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_LISTALLESTIMATORSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct listAllEstimatorsRequest_
{
  typedef listAllEstimatorsRequest_<ContainerAllocator> Type;

  listAllEstimatorsRequest_()
    {
    }
  listAllEstimatorsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct listAllEstimatorsRequest_

typedef ::state_estimator_msgs::listAllEstimatorsRequest_<std::allocator<void> > listAllEstimatorsRequest;

typedef boost::shared_ptr< ::state_estimator_msgs::listAllEstimatorsRequest > listAllEstimatorsRequestPtr;
typedef boost::shared_ptr< ::state_estimator_msgs::listAllEstimatorsRequest const> listAllEstimatorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/listAllEstimatorsRequest";
  }

  static const char* value(const ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct listAllEstimatorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::state_estimator_msgs::listAllEstimatorsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_LISTALLESTIMATORSREQUEST_H
