// Generated by gencpp from file state_estimator_msgs/pauseEstimator.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_PAUSEESTIMATOR_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_PAUSEESTIMATOR_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/pauseEstimatorRequest.h>
#include <state_estimator_msgs/pauseEstimatorResponse.h>


namespace state_estimator_msgs
{

struct pauseEstimator
{

typedef pauseEstimatorRequest Request;
typedef pauseEstimatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pauseEstimator
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::pauseEstimator > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::state_estimator_msgs::pauseEstimator&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::pauseEstimator > {
  static const char* value()
  {
    return "state_estimator_msgs/pauseEstimator";
  }

  static const char* value(const ::state_estimator_msgs::pauseEstimator&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::pauseEstimatorRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::pauseEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::pauseEstimatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::pauseEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::pauseEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::pauseEstimatorRequest> should match
// service_traits::DataType< ::state_estimator_msgs::pauseEstimator >
template<>
struct DataType< ::state_estimator_msgs::pauseEstimatorRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::pauseEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::pauseEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::pauseEstimatorResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::pauseEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::pauseEstimatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::pauseEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::pauseEstimatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::pauseEstimatorResponse> should match
// service_traits::DataType< ::state_estimator_msgs::pauseEstimator >
template<>
struct DataType< ::state_estimator_msgs::pauseEstimatorResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::pauseEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::pauseEstimatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_PAUSEESTIMATOR_H
