// Generated by gencpp from file state_estimator_msgs/resetEstimator.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_RESETESTIMATOR_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_RESETESTIMATOR_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/resetEstimatorRequest.h>
#include <state_estimator_msgs/resetEstimatorResponse.h>


namespace state_estimator_msgs
{

struct resetEstimator
{

typedef resetEstimatorRequest Request;
typedef resetEstimatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct resetEstimator
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::resetEstimator > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::state_estimator_msgs::resetEstimator&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::resetEstimator > {
  static const char* value()
  {
    return "state_estimator_msgs/resetEstimator";
  }

  static const char* value(const ::state_estimator_msgs::resetEstimator&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::resetEstimatorRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::resetEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::resetEstimatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::resetEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::resetEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::resetEstimatorRequest> should match
// service_traits::DataType< ::state_estimator_msgs::resetEstimator >
template<>
struct DataType< ::state_estimator_msgs::resetEstimatorRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::resetEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::resetEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::resetEstimatorResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::resetEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::resetEstimatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::resetEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::resetEstimatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::resetEstimatorResponse> should match
// service_traits::DataType< ::state_estimator_msgs::resetEstimator >
template<>
struct DataType< ::state_estimator_msgs::resetEstimatorResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::resetEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::resetEstimatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_RESETESTIMATOR_H
