// Generated by gencpp from file state_estimator_msgs/restartEstimator.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_RESTARTESTIMATOR_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_RESTARTESTIMATOR_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/restartEstimatorRequest.h>
#include <state_estimator_msgs/restartEstimatorResponse.h>


namespace state_estimator_msgs
{

struct restartEstimator
{

typedef restartEstimatorRequest Request;
typedef restartEstimatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct restartEstimator
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::restartEstimator > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::state_estimator_msgs::restartEstimator&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::restartEstimator > {
  static const char* value()
  {
    return "state_estimator_msgs/restartEstimator";
  }

  static const char* value(const ::state_estimator_msgs::restartEstimator&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::restartEstimatorRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::restartEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::restartEstimatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::restartEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::restartEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::restartEstimatorRequest> should match
// service_traits::DataType< ::state_estimator_msgs::restartEstimator >
template<>
struct DataType< ::state_estimator_msgs::restartEstimatorRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::restartEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::restartEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::restartEstimatorResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::restartEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::restartEstimatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::restartEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::restartEstimatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::restartEstimatorResponse> should match
// service_traits::DataType< ::state_estimator_msgs::restartEstimator >
template<>
struct DataType< ::state_estimator_msgs::restartEstimatorResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::restartEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::restartEstimatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_RESTARTESTIMATOR_H
