// Generated by gencpp from file state_estimator_msgs/resumeEstimator.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_RESUMEESTIMATOR_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_RESUMEESTIMATOR_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/resumeEstimatorRequest.h>
#include <state_estimator_msgs/resumeEstimatorResponse.h>


namespace state_estimator_msgs
{

struct resumeEstimator
{

typedef resumeEstimatorRequest Request;
typedef resumeEstimatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct resumeEstimator
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::resumeEstimator > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::state_estimator_msgs::resumeEstimator&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::resumeEstimator > {
  static const char* value()
  {
    return "state_estimator_msgs/resumeEstimator";
  }

  static const char* value(const ::state_estimator_msgs::resumeEstimator&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::resumeEstimatorRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::resumeEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::resumeEstimatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::resumeEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::resumeEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::resumeEstimatorRequest> should match
// service_traits::DataType< ::state_estimator_msgs::resumeEstimator >
template<>
struct DataType< ::state_estimator_msgs::resumeEstimatorRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::resumeEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::resumeEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::resumeEstimatorResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::resumeEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::resumeEstimatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::resumeEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::resumeEstimatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::resumeEstimatorResponse> should match
// service_traits::DataType< ::state_estimator_msgs::resumeEstimator >
template<>
struct DataType< ::state_estimator_msgs::resumeEstimatorResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::resumeEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::resumeEstimatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_RESUMEESTIMATOR_H
