// Generated by gencpp from file state_estimator_msgs/startEstimator.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_STARTESTIMATOR_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_STARTESTIMATOR_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/startEstimatorRequest.h>
#include <state_estimator_msgs/startEstimatorResponse.h>


namespace state_estimator_msgs
{

struct startEstimator
{

typedef startEstimatorRequest Request;
typedef startEstimatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct startEstimator
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::startEstimator > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::state_estimator_msgs::startEstimator&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::startEstimator > {
  static const char* value()
  {
    return "state_estimator_msgs/startEstimator";
  }

  static const char* value(const ::state_estimator_msgs::startEstimator&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::startEstimatorRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::startEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::startEstimatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::startEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::startEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::startEstimatorRequest> should match
// service_traits::DataType< ::state_estimator_msgs::startEstimator >
template<>
struct DataType< ::state_estimator_msgs::startEstimatorRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::startEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::startEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::startEstimatorResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::startEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::startEstimatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::startEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::startEstimatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::startEstimatorResponse> should match
// service_traits::DataType< ::state_estimator_msgs::startEstimator >
template<>
struct DataType< ::state_estimator_msgs::startEstimatorResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::startEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::startEstimatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_STARTESTIMATOR_H
