// Generated by gencpp from file state_estimator_msgs/stopEstimator.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_STOPESTIMATOR_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_STOPESTIMATOR_H

#include <ros/service_traits.h>


#include <state_estimator_msgs/stopEstimatorRequest.h>
#include <state_estimator_msgs/stopEstimatorResponse.h>


namespace state_estimator_msgs
{

struct stopEstimator
{

typedef stopEstimatorRequest Request;
typedef stopEstimatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stopEstimator
} // namespace state_estimator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator_msgs::stopEstimator > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::state_estimator_msgs::stopEstimator&) { return value(); }
};

template<>
struct DataType< ::state_estimator_msgs::stopEstimator > {
  static const char* value()
  {
    return "state_estimator_msgs/stopEstimator";
  }

  static const char* value(const ::state_estimator_msgs::stopEstimator&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator_msgs::stopEstimatorRequest> should match
// service_traits::MD5Sum< ::state_estimator_msgs::stopEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::stopEstimatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::stopEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::stopEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::stopEstimatorRequest> should match
// service_traits::DataType< ::state_estimator_msgs::stopEstimator >
template<>
struct DataType< ::state_estimator_msgs::stopEstimatorRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::stopEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::stopEstimatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator_msgs::stopEstimatorResponse> should match
// service_traits::MD5Sum< ::state_estimator_msgs::stopEstimator >
template<>
struct MD5Sum< ::state_estimator_msgs::stopEstimatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator_msgs::stopEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::stopEstimatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator_msgs::stopEstimatorResponse> should match
// service_traits::DataType< ::state_estimator_msgs::stopEstimator >
template<>
struct DataType< ::state_estimator_msgs::stopEstimatorResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator_msgs::stopEstimator >::value();
  }
  static const char* value(const ::state_estimator_msgs::stopEstimatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_STOPESTIMATOR_H
