// Generated by gencpp from file state_estimator/RollPitchStamped.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MESSAGE_ROLLPITCHSTAMPED_H
#define STATE_ESTIMATOR_MESSAGE_ROLLPITCHSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <state_estimator/RollPitch.h>

namespace state_estimator
{
template <class ContainerAllocator>
struct RollPitchStamped_
{
  typedef RollPitchStamped_<ContainerAllocator> Type;

  RollPitchStamped_()
    : header()
    , rollpitch()  {
    }
  RollPitchStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rollpitch(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::state_estimator::RollPitch_<ContainerAllocator>  _rollpitch_type;
  _rollpitch_type rollpitch;





  typedef boost::shared_ptr< ::state_estimator::RollPitchStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator::RollPitchStamped_<ContainerAllocator> const> ConstPtr;

}; // struct RollPitchStamped_

typedef ::state_estimator::RollPitchStamped_<std::allocator<void> > RollPitchStamped;

typedef boost::shared_ptr< ::state_estimator::RollPitchStamped > RollPitchStampedPtr;
typedef boost::shared_ptr< ::state_estimator::RollPitchStamped const> RollPitchStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator::RollPitchStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator::RollPitchStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator::RollPitchStamped_<ContainerAllocator1> & lhs, const ::state_estimator::RollPitchStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rollpitch == rhs.rollpitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator::RollPitchStamped_<ContainerAllocator1> & lhs, const ::state_estimator::RollPitchStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator::RollPitchStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator::RollPitchStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator::RollPitchStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator::RollPitchStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator::RollPitchStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator::RollPitchStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator::RollPitchStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b6120207ee622e95692282f4b59fcc9";
  }

  static const char* value(const ::state_estimator::RollPitchStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b6120207ee622e9ULL;
  static const uint64_t static_value2 = 0x5692282f4b59fcc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator::RollPitchStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator/RollPitchStamped";
  }

  static const char* value(const ::state_estimator::RollPitchStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator::RollPitchStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"RollPitch rollpitch\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: state_estimator/RollPitch\n"
"float64 roll\n"
"float64 pitch\n"
;
  }

  static const char* value(const ::state_estimator::RollPitchStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator::RollPitchStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rollpitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RollPitchStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator::RollPitchStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator::RollPitchStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rollpitch: ";
    s << std::endl;
    Printer< ::state_estimator::RollPitch_<ContainerAllocator> >::stream(s, indent + "  ", v.rollpitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MESSAGE_ROLLPITCHSTAMPED_H
