// Generated by gencpp from file state_estimator/RollPitch.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MESSAGE_ROLLPITCH_H
#define STATE_ESTIMATOR_MESSAGE_ROLLPITCH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_estimator
{
template <class ContainerAllocator>
struct RollPitch_
{
  typedef RollPitch_<ContainerAllocator> Type;

  RollPitch_()
    : roll(0.0)
    , pitch(0.0)  {
    }
  RollPitch_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::state_estimator::RollPitch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator::RollPitch_<ContainerAllocator> const> ConstPtr;

}; // struct RollPitch_

typedef ::state_estimator::RollPitch_<std::allocator<void> > RollPitch;

typedef boost::shared_ptr< ::state_estimator::RollPitch > RollPitchPtr;
typedef boost::shared_ptr< ::state_estimator::RollPitch const> RollPitchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator::RollPitch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator::RollPitch_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator::RollPitch_<ContainerAllocator1> & lhs, const ::state_estimator::RollPitch_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator::RollPitch_<ContainerAllocator1> & lhs, const ::state_estimator::RollPitch_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator::RollPitch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator::RollPitch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator::RollPitch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator::RollPitch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator::RollPitch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator::RollPitch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator::RollPitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f5aa311af37faead3f9e90f420c9603";
  }

  static const char* value(const ::state_estimator::RollPitch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f5aa311af37faeaULL;
  static const uint64_t static_value2 = 0xd3f9e90f420c9603ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator::RollPitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator/RollPitch";
  }

  static const char* value(const ::state_estimator::RollPitch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator::RollPitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n"
"float64 pitch\n"
;
  }

  static const char* value(const ::state_estimator::RollPitch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator::RollPitch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RollPitch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator::RollPitch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator::RollPitch_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MESSAGE_ROLLPITCH_H
