float64[3] knee_ang_vel_RF
float64[3] knee_ang_vel_RH
float64[3] knee_ang_vel_LH
float64[3] knee_ang_vel_LF



float64[3] foot_linear_acc_tot
float64[9] foot_jac

float64 debug_foot_pos_lh_x
float64 debug_foot_pos_lh_y
float64 debug_foot_pos_lh_z
float64 debug_foot_pos_rf_x
float64 debug_foot_pos_rf_y
float64 debug_foot_pos_rf_z

float64 debug_foot_pos_lf_x
float64 debug_foot_pos_lf_y
float64 debug_foot_pos_lf_z
float64 debug_foot_pos_rh_x
float64 debug_foot_pos_rh_y
float64 debug_foot_pos_rh_z

float64 shin_angle_rf0
float64 shin_angle_rf1
float64 shin_angle_rf2

float64 shin_angle_rh0
float64 shin_angle_rh1
float64 shin_angle_rh2

float64 shin_angle_lh0
float64 shin_angle_lh1
float64 shin_angle_lh2

float64 shin_angle_lf0
float64 shin_angle_lf1
float64 shin_angle_lf2

float64 acc_lh0
float64 acc_lh1
float64 acc_lh2

float64 acc_rh0
float64 acc_rh1
float64 acc_rh2

float64 acc_lf0
float64 acc_lf1
float64 acc_lf2

float64 acc_rf0
float64 acc_rf1
float64 acc_rf2
